# Generated by Django 2.1.5 on 2019-01-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendary_roster', models.ImageField(upload_to='images/')),
                ('rexx_summary', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('ds_contact', models.CharField(max_length=20)),
                ('rec_summary', models.CharField(max_length=200)),
            ],
        ),
    ]
